### ISSUE TITLE
hoverd doesn't work on kernel 4.4 

### ISSUE THREAD

**Issue by dkalani** [iovisor/iomodules#7]

**Comment by drzaeus77** [comment]
Change pushed, please test and close.

**Comment by tarekrabia** [comment]
Hello 

i'm using kernel 4.4 and i'm trying to setup iomodules. So, i'm following your tutorial but when i run 
go install github.com/iovisor/iomodules/hover/hoverd
i get this error : can't load package: package github.com/iovisor/iomodules/hover/hoverd: found packages main (main.go) and hover (server.go)
can someone help me, please.
Thank you 
Best regards 
Tarek RABIA

**Comment by drzaeus77** [comment]
Hi, sorry, I had left a deprecated file around. Please pull the latest and
re-test.

**Comment by dkalani** [comment]
tested and now works with 4.4

**Comment by tarekrabia** [comment]
Thank you for answer 

Best regards 
Tarek

**Comment by tarekrabia** [comment]
hello again 
i have some problems, I got this error : 
$GOPATH/src/github.com/iovisor/iomodules/hover/daemon/server.go:20:2: cannot find package "github.com/gorilla/mux"

Best Regards 
Tarek

**Comment by dkalani** [comment]
did you clone the repo or do

go get github.com/iovisor/iomodules/hover

alternatively you can resolve dependencies by using gosub
<https://github.com/vito/gosub>

 and fetching all dependencies.

Deepa

**Comment by tarekrabia** [comment]
Hello 
Now it works well !!!! you just download and copy this two folders in $GOPATH/src/github.com/gorilla/
git clone https://github.com/gorilla/mux.git
git clone https://github.com/gorilla/context.git

Thank you again for your precious help

Best regards
Tarek
